package net.brdle.collectorsreap.client.animation;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

@OnlyIn(Dist.CLIENT)
public class ChieftainCrabAnimation {
	public static final AnimationDefinition CHIEFTAINCRAB_WALK = AnimationDefinition.Builder.withLength(0.44f).looping()
		.addAnimation("Body",
			new AnimationChannel(AnimationChannel.Targets.POSITION,
				new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.04f, KeyframeAnimations.posVec(0f, -0.1f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.08f, KeyframeAnimations.posVec(0f, -0.2f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.12f, KeyframeAnimations.posVec(0f, -0.4f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.16f, KeyframeAnimations.posVec(0f, -0.8f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2f, KeyframeAnimations.posVec(0f, -1.2f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.28f, KeyframeAnimations.posVec(0f, -0.1f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.32f, KeyframeAnimations.posVec(0f, -0.2f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.36f, KeyframeAnimations.posVec(0f, -0.4f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4f, KeyframeAnimations.posVec(0f, -0.8f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("LeftArm2",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.04f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.08f, KeyframeAnimations.degreeVec(17.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.12f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.16f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2f, KeyframeAnimations.degreeVec(24f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.24f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.28f, KeyframeAnimations.degreeVec(19f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.32f, KeyframeAnimations.degreeVec(11.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.36f, KeyframeAnimations.degreeVec(6.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4f, KeyframeAnimations.degreeVec(4f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.44f, KeyframeAnimations.degreeVec(1.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("bone3",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -20f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("RightArm2",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.04f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.08f, KeyframeAnimations.degreeVec(17.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.12f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.16f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2f, KeyframeAnimations.degreeVec(24f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.24f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.28f, KeyframeAnimations.degreeVec(19f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.32f, KeyframeAnimations.degreeVec(11.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.36f, KeyframeAnimations.degreeVec(6.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4f, KeyframeAnimations.degreeVec(4f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.44f, KeyframeAnimations.degreeVec(1.5f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("bone2",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 20f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("RightLeg1",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, 7.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("RightLeg2",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 7.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4f, KeyframeAnimations.degreeVec(0f, 0f, 7.5f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("RightLeg3",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, 7.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("RightLeg4",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 7.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4f, KeyframeAnimations.degreeVec(0f, 0f, 7.5f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("LeftLeg1",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("LeftLeg2",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("LeftLeg3",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
					AnimationChannel.Interpolations.LINEAR)))
		.addAnimation("LeftLeg4",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition CHIEFTAINCRAB_IDLE = AnimationDefinition.Builder.withLength(2.6f).looping()
		.addAnimation("LeftArm",
			new AnimationChannel(AnimationChannel.Targets.ROTATION,
				new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR),
				new Keyframe(0.36f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
					AnimationChannel.Interpolations.LINEAR))).build();
}
